# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2327b48060a33c6b2246b84df888634ba64c758ac8d3333a783c25c3361b5b25a9dd73cbb2e37b349a0e2f65316874d6dfc855ae365da3838cccfe01ef3ef989

test:
  secret_key_base: 846dab59880ac566a62df538a98b2bb5fdce0543421b3c5e6fcf21b203d6b2470a308077ce8eae4683d1145cfb5f9ab92dc49f51df383aaf1318234d8c53d3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
